version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:17.4.0
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: shop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:7.4.2
    container_name: redis_cache
    restart: always
    command: redis-server --requirepass 1234
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    environment:
      - REDIS_PASSWORD=1234

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
